#:schema node_modules/wrangler/config-schema.json
name = "remix-memo"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-10-18"
main = "./build/worker/index.js"
assets = { directory = "./build/client" }
vars = { ENVIRONMENT = "production" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "remix-memo"
database_id = "87789fb3-c810-4d74-aa86-56cb65332c83"

[[kv_namespaces]]
binding = "KV"
id = "cb90160337d14cb6bc9f27b680a38dde"
